on: [push]

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        uses: actions-rs/clippy-check@v1