on: [push]

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
            
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features